
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=hashCode_4eab0d4f68
ROOST_METHOD_SIG_HASH=hashCode_44411a81c8


Scenario 1: Validate hashCode returns consistent value for an unchanged object

Details:
  TestName: validateHashCodeConsistencyForUnchangedObject
  Description: This test confirms that the hashCode method returns a consistent value when the object state is not modified. It ensures the integrity of hashCode calculations for immutable scenarios.

Execution:
  Arrange: Create an instance of CredentialsObscuredGet200Response with a pre-defined state.
  Act: Generate the hashCode twice without changing the object state.
  Assert: Compare the two hashCode values to ensure they are equal.

Validation:
  This test verifies that the hashCode method maintains consistency for a given object when its state does not change. It is essential because inconsistent hashCode results can cause issues in data structures like hash-based collections (e.g., HashMap, HashSet).

*/

// ********RoostGPT********

package org.openapitools.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class CredentialsObscuredGet200ResponseHashCodeTest {

	@Test
	@Tag("valid")
	public void validateHashCodeConsistencyForUnchangedObject() {
		// Arrange
		Boolean initialObscuredValue = true; // TODO: Customize the obscured value if
												// required
		CredentialsObscuredGet200Response response = new CredentialsObscuredGet200Response()
			.obscured(initialObscuredValue);
		// Act
		int hashCodeFirstCall = response.hashCode();
		int hashCodeSecondCall = response.hashCode();
		// Assert
		assertEquals(hashCodeFirstCall, hashCodeSecondCall, "HashCodes should be consistent for an unchanged object.");
	}

}