
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-testing using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=equals_c359bb3fac
ROOST_METHOD_SIG_HASH=equals_ded257778a

Scenario 1: Check equality of two identical objects

Details:
  TestName: checkEqualityOfIdenticalObjects
  Description: Verifies that the equals method returns true when comparing an object to itself. This tests the reflexive property of equality.

Execution:
  Arrange: Create a single instance of LoginButtonStatusGet200Response and set its `status` field to a specific value, such as "active".
  Act: Call the equals method on the object, comparing it to itself.
  Assert: Assert that the resulting value of equals is true.
Validation:
  Verifies that the method properly handles self-referential comparisons, ensuring objects are inherently equal to themselves. This is crucial for maintaining the integrity of the equality logic.

*/

// ********RoostGPT********

package org.openapitools.model;

import org.openapitools.model.LoginButtonStatusGet200Response;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import javax.annotation.Generated;

public class LoginButtonStatusGet200ResponseEqualsTest {

	@Test
	@Tag("valid")
	public void checkEqualityOfIdenticalObjects() {
		// Arrange
		LoginButtonStatusGet200Response instance = new LoginButtonStatusGet200Response().status("active"); // TODO
																											// Change
																											// "active"
																											// to
																											// any
																											// other
																											// value
																											// if
																											// needed.
		// Act
		boolean result = instance.equals(instance);
		// Assert
		assertTrue(result, "The equals method should return true when comparing an object to itself.");
	}

}